# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mnTS_ml_cpp <- function(par, par_fixed, Y, X, Tsample) {
    .Call(`_multinomialTS_mnTS_ml_cpp`, par, par_fixed, Y, X, Tsample)
}

mnTS_ml_cpp_list <- function(par, par_fixed, Y, X, Tsample) {
    .Call(`_multinomialTS_mnTS_ml_cpp_list`, par, par_fixed, Y, X, Tsample)
}

