name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: Rscript -e 'install.packages(c("devtools", "remotes"))'

      - name: Build package
        run: Rscript -e 'devtools::build(binary = TRUE)'

      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: multinomialTS
          path: |
            *.zip
            *.tgz
            *.tar.gz
        continue-on-error: true

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Release Assets
        uses: actions/download-artifact@v2
        with:
          name: multinomialTS

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
            *.tgz
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
