name: Build Binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install libomp
          brew install gcc

      - name: Install R package dependencies
        run: Rscript -e 'install.packages(c("devtools", "remotes", "RcppArmadillo", "minqa", "matrixStats", "numDeriv", "mvtnorm"))'

      - name: Clean previous builds
        run: Rscript -e 'devtools::clean_dll()'

      - name: Build package with verbose output
        run: Rscript -e 'devtools::build(binary = TRUE, args = c("--no-multiarch", "--preclean", "--clean", "--verbose"))'

      - name: Upload Release Asset (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: multinomialTS-macOS
          path: |
            *.tgz
            *.tar.gz

      - name: Upload Release Asset (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: multinomialTS-Windows
          path: D:/a/multinomialTS/multinomialTS_0.1.0.zip

      - name: List Uploaded Artifacts (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          if ls -l *.tgz *.tar.gz 2>/dev/null; then echo "Artifacts listed successfully"; else echo "No artifacts to list"; fi

      - name: List Uploaded Artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          if (Test-Path -Path D:/a/multinomialTS/multinomialTS_0.1.0.zip) { Get-ChildItem -Path D:/a/multinomialTS/multinomialTS_0.1.0.zip } else { Write-Output "No artifacts to list" }

  release:
    runs-on: ubuntu-latest
    needs: build  # Ensures this job runs after the build job

    steps:
      - name: Download macOS Release Assets
        uses: actions/download-artifact@v2
        with:
          name: multinomialTS-macOS

      - name: Download Windows Release Assets
        uses: actions/download-artifact@v2
        with:
          name: multinomialTS-Windows

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
            *.tgz
            *.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
