name: Build Binaries

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: # Enables manual runs for GHA debugging

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install libomp
          brew install gcc

      - name: Install R package dependencies
        run: Rscript -e 'install.packages(c("devtools", "remotes", "RcppArmadillo", "minqa", "matrixStats", "numDeriv", "mvtnorm"))'

      - name: Clean previous builds
        run: Rscript -e 'devtools::clean_dll()'

      - name: Build package with verbose output
        run: Rscript -e 'devtools::build(binary = TRUE, args = c("--no-multiarch", "--preclean", "--clean", "--verbose"))'

      - name: List all files after build
        run: ls -R

      - name: Upload Release Asset (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: multinomialTS-macOS
          path: /Users/runner/work/multinomialTS/multinomialTS_*.tgz  # Adjusted wildcard path for macOS
          if-no-files-found: error
        env:
          R_LIBS_USER: /Users/runner/work/_temp/Library
          TZ: UTC
          _R_CHECK_SYSTEM_CLOCK_: FALSE
          NOT_CRAN: true

      - name: Upload Release Asset (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: multinomialTS-Windows
          path: D:/a/multinomialTS/multinomialTS_*.zip  # Adjusted wildcard path for Windows

  release:
    runs-on: ubuntu-latest
    needs: build  # Ensures this job runs after the build job

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: /home/runner/work/multinomialTS/

      - name: Show artifacts
        run: find /home/runner/work/multinomialTS/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          files: |
            /home/runner/work/multinomialTS/multinomialTS-macOS/*.tgz
            /home/runner/work/multinomialTS/multinomialTS-Windows/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
